//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Replies = new HashSet<Reply>();
        }
    
        public int PostID { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<Reply> Replies { get; set; }
    }
}
